### ISSUE TITLE
HFCurationRequest PopulationID required

### ISSUE THREAD

**Issue by hpeberhard** [nmdp-bioinformatics/service-haplotype-frequency-curation#19]
I am struggling with the fact that the PopulationID of the HFCurationRequest is required where I believe the request either uses the PopulationID (provided by the server) or a reference to PopulationData (upload use case).

**Comment by mmaiers-nmdp** [comment]
Additionally, it appears that PopulationID is "Required" according to the yaml (lines 222-223) but the code generated does not enforce it

**Comment by mmaiers-nmdp** [comment]
Instead of having a separate service for population ID, we can add a "POST /population" endpoint to this service.

If you call POST /population with a populationRequest
{
  "description": "string",
  "name": "string"
}

you get back a populationId (integer)

Then we can get rid of PopulationData as option to POST /hfc
Only have this one:

  "PopulationID": "integer”, (change from string to integer)

get rid of this one:
  "PopulationData": {
    "id": "string",
    "name": "string"
  },

**Comment by fscheel** [comment]
This should be more clear/fixed now with the implementation of the `/population` endpoints.
