### ISSUE TITLE
Should the clients be checked in with the service?

### ISSUE THREAD

**Issue by mpresteg** [nmdp-bioinformatics/service-haplotype-frequency-curation#47]
It implies that maintenance of the clients be synchronized with the service, which increases the burden for anyone modifying the service.  There is value to the synchronization, but separation seems more appropriate.

**Comment by mmaiers-nmdp** [comment]
This came up at the meeting on Nov 7.  The naming convention for github repos (service-foo, client-foo) is being intentionally violated for phycus since for this project we are tightly coupling both the client API and the server API to the YAML.  Having the API code be swagger-generated as much as possible will reduce the impact down the road when we make changes to the model.

We will reduce the churn of having the regenerate client API code if we take things like enumerated value domains out of the YAML. 

for example:
```enum:
          - DIV_LAMBDA
          - DIV_50
          - DIV_50_REL
          - SAM_SIZE
          - SAM_POP
          - DIV_PGD
          - DIV_HEAVY_TAIL
          - RES_TRS_COUNT
          - RES_TRS
          - RES_SHARE_AMBIG
          - RES_MISS_LOCI
          - DEV_HWE
          - ERR_STD
          - ERR_SAMP_80_100
          - SUM_FREQ_GAP
          - ERR_OFFSET
          - LD_MEASURE
          - KFOLD_IMPUTE
          - KFOLD_PRED_ACTUAL
          - KFOLD_N
```

**Comment by fscheel** [comment]
Taking those enumerations out of the specs, this would also help with https://github.com/nmdp-bioinformatics/service-haplotype-frequency-curation/issues/15#issuecomment-344217377, but we'd have to document the value domain seprately.

**Comment by mpresteg** [comment]
Closing - Java client with swagger code gen built in via Maven added to the service (status:  pull request review).  Command line tools added in multi-module java client.
